In [30]:
import pandas

In [37]:
google_app= pandas.read_table("googleplaystore.csv",sep=",")
google_app

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [38]:
google_app_sans_na = google_app.dropna()

In [39]:
google_app_sans_na["Price"]=google_app_sans_na["Price"].apply(lambda x: x.replace("$" , ""))
google_app_sans_na["Price"]=google_app_sans_na["Price"].apply(lambda x: float(x))

C:\Users\nico\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\nico\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [40]:
google_app_sans_na["Reviews"]=google_app_sans_na["Reviews"].apply(lambda x: int(x))

C:\Users\nico\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [41]:
google_app_sans_na["Installs"]=google_app_sans_na["Installs"].apply(lambda x: x.replace("," , ""))
google_app_sans_na["Installs"]=google_app_sans_na["Installs"].apply(lambda x: x.replace("+" , ""))

C:\Users\nico\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\nico\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [42]:
google_app_sans_na["Installs"]=google_app_sans_na["Installs"].apply(lambda x: int(x))

C:\Users\nico\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [43]:
google_app_sans_na

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6M,500,Free,0.0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,5000,Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000,Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [14]:
#question 1 noms,categories et genre des apply les plus installes
apply_max_installer=max(google_app_sans_na["Installs"])
google_app_sans_na.loc[(google_app_sans_na["Installs"]==apply_max_installer),["App","Category","Genre"]].head()

C:\Users\nico\Anaconda3\lib\site-packages\pandas\core\indexing.py:1418: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

                                          App             Category  Genre
152                         Google Play Books  BOOKS_AND_REFERENCE    NaN
335  Messenger – Text and Video Chat for Free        COMMUNICATION    NaN
336                        WhatsApp Messenger        COMMUNICATION    NaN
338              Google Chrome: Fast & Secure        COMMUNICATION    NaN
340                                     Gmail        COMMUNICATION    NaN

In [15]:
#question 2 le plsu grand nbr de reviews et nom , note globale de lapplly
apply_max_reviews = max(google_app_sans_na["Reviews"])
google_app_sans_na.loc[google_app_sans_na["Reviews"]==apply_max_reviews,["App","Rating"]]

           App  Rating
2544  Facebook     4.1

In [16]:
apply_max_reviews

78158306

In [17]:
#question 3 afficher les colonnes 2,5,6 et les lgines de 3 a 16
google_app_sans_na.iloc[2:16,[1,4,5]]

          Category  Size  Installs
2   ART_AND_DESIGN  8.7M   5000000
3   ART_AND_DESIGN   25M  50000000
4   ART_AND_DESIGN  2.8M    100000
5   ART_AND_DESIGN  5.6M     50000
6   ART_AND_DESIGN   19M     50000
7   ART_AND_DESIGN   29M   1000000
8   ART_AND_DESIGN   33M   1000000
9   ART_AND_DESIGN  3.1M     10000
10  ART_AND_DESIGN   28M   1000000
11  ART_AND_DESIGN   12M   1000000
12  ART_AND_DESIGN   20M  10000000
13  ART_AND_DESIGN   21M    100000
14  ART_AND_DESIGN   37M    100000
16  ART_AND_DESIGN  5.5M    500000

In [18]:
# question 4 combien dapply accessible a tout le monde
sum(google_app_sans_na["Content Rating"]=="Everyone")

7414

In [19]:
# question 5 quelle categorie a le + dapllication 
google_app_sans_na.groupby("Category").agg(["count"])

,App,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
,count,count,count,count,count,count,count,count,count,count,count,count
Category,,,,,,,,,,,,
ART_AND_DESIGN,61,61,61,61,61,61,61,61,61,61,61,61
AUTO_AND_VEHICLES,73,73,73,73,73,73,73,73,73,73,73,73
BEAUTY,42,42,42,42,42,42,42,42,42,42,42,42
BOOKS_AND_REFERENCE,178,178,178,178,178,178,178,178,178,178,178,178
BUSINESS,303,303,303,303,303,303,303,303,303,303,303,303
COMICS,58,58,58,58,58,58,58,58,58,58,58,58
COMMUNICATION,328,328,328,328,328,328,328,328,328,328,328,328
DATING,195,195,195,195,195,195,195,195,195,195,195,195
EDUCATION,155,155,155,155,155,155,155,155,155,155,155,155
ENTERTAINMENT,149,149,149,149,149,149,149,149,149,149,149,149
EVENTS,45,45,45,45,45,45,45,45,45,45,45,45
FAMILY,1746,1746,1746,1746,1746,1746,1746,1746,1746,1746,1746,1746
FINANCE,323,323,323,323,323,323,323,323,323,323,323,323
FOOD_AND_DRINK,109,109,109,109,109,109,109,109,109,109,109,109
GAME,1097,1097,1097,1097,1097,1097,1097,1097,1097,1097,1097,1097
HEALTH_AND_FITNESS,297,297,297,297,297,297,297,297,297,297,297,297
HOUSE_AND_HOME,76,76,76,76,76,76,76,76,76,76,76,76
LIBRARIES_AND_DEMO,64,64,64,64,64,64,64,64,64,64,64,64
LIFESTYLE,314,314,314,314,314,314,314,314,314,314,314,314
MAPS_AND_NAVIGATION,124,124,124,124,124,124,124,124,124,124,124,124
MEDICAL,350,350,350,350,350,350,350,350,350,350,350,350
NEWS_AND_MAGAZINES,233,233,233,233,233,233,233,233,233,233,233,233
PARENTING,50,50,50,50,50,50,50,50,50,50,50,50
PERSONALIZATION,312,312,312,312,312,312,312,312,312,312,312,312
PHOTOGRAPHY,317,317,317,317,317,317,317,317,317,317,317,317
PRODUCTIVITY,351,351,351,351,351,351,351,351,351,351,351,351
SHOPPING,238,238,238,238,238,238,238,238,238,238,238,238
SOCIAL,259,259,259,259,259,259,259,259,259,259,259,259
SPORTS,319,319,319,319,319,319,319,319,319,319,319,319
TOOLS,733,733,733,733,733,733,733,733,733,733,733,733
TRAVEL_AND_LOCAL,226,226,226,226,226,226,226,226,226,226,226,226
VIDEO_PLAYERS,160,160,160,160,160,160,160,160,160,160,160,160
WEATHER,75,75,75,75,75,75,75,75,75,75,75,75

In [20]:
#6 quelle est l appli la plus cher
apply_plus_cher=max(google_app_sans_na["Price"])
print(apply_plus_cher)
google_app_sans_na[google_app_sans_na["Price"]==apply_plus_cher]

400.0

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4367,I'm Rich - Trump Edition,LIFESTYLE,3.6,275,7.3M,10000,Paid,400.0,Everyone,Lifestyle,"May 3, 2018",1.0.1,4.1 and up